### ISSUE TITLE
About using OSCQuery

### ISSUE THREAD

**Issue by maemoKKK** [yewnyx/SubLink#5]
Sorry for my interrupt.

I wonder. Do you know how to let OSCQuery work? 

"/tracking/vrsystem" does work for me

**Comment by LauraRozier** [comment]
Did you check the docs?
https://github.com/yewnyx/SubLink/blob/master/Docs/oscQuery_and_oscServer.md

If you have any specific needs/questions please do ask. :)

**Comment by maemoKKK** [comment]
I'm very very very  appreciate for your kindly reply. I have read spec. 

I aslo read a lot on [vrc-oscquery-lib](https://github.com/vrchat-community/vrc-oscquery-lib/tree/30029455b6cfb68fe51d2bce72e886d2f43d13b8)/[Examples](https://github.com/vrchat-community/vrc-oscquery-lib/tree/30029455b6cfb68fe51d2bce72e886d2f43d13b8/Examples)/[OSCQueryExplorer-Unity](https://github.com/vrchat-community/vrc-oscquery-lib/tree/30029455b6cfb68fe51d2bce72e886d2f43d13b8/Examples/OSCQueryExplorer-Unity)/[Assets](https://github.com/vrchat-community/vrc-oscquery-lib/tree/30029455b6cfb68fe51d2bce72e886d2f43d13b8/Examples/OSCQueryExplorer-Unity/Assets)/[OSCQuery](https://github.com/vrchat-community/vrc-oscquery-lib/tree/30029455b6cfb68fe51d2bce72e886d2f43d13b8/Examples/OSCQueryExplorer-Unity/Assets/OSCQuery)/[Samples](https://github.com/vrchat-community/vrc-oscquery-lib/tree/30029455b6cfb68fe51d2bce72e886d2f43d13b8/Examples/OSCQueryExplorer-Unity/Assets/OSCQuery/Samples)/[Tracking](https://github.com/vrchat-community/vrc-oscquery-lib/tree/30029455b6cfb68fe51d2bce72e886d2f43d13b8/Examples/OSCQueryExplorer-Unity/Assets/OSCQuery/Samples/Tracking)
/HeadAndWristsReceiver.cs

I aslo use official unity example, but HeadAndWristsReceiver doesn't work. although the example pose sender can work in official github exmample.

I can't find anything related with this, but I find you.

Did you run official sample susccessfully? 

Reccently, when I run official sample, there is no HUB or notice in VRCHAT on quest2 or quest3.

**Comment by LauraRozier** [comment]
I haven't tested that part too extensively. When using the Quest do you also use the Quest link cable, Virtual Desktop or are you trying to query from the PC to a standalone Quest? I personally didn't try the sample, just the implementation we have in SubLink.

**Comment by maemoKKK** [comment]
I'm trying to query from the PC to a standalone Quest. 

I have took a glance at your code. haven't find query head and wrist pose from quest VRChat.

**Comment by LauraRozier** [comment]
I just tested head/pose to a Quest 2 using Virtual Desktop and that works fine.
check: https://github.com/yewnyx/SubLink/blob/master/SubLinkCommon/OSCQueryService.cs
